// @qi/core — pure domain logic ported from MDA-Inventory. No IO, no DB, no React.
export { brand } from './brand.ts';
export { round2, roundOff, roundHalfAway } from './round.ts';
export { hashPassword, verifyPassword, isLegacyPassword } from './password.ts';
export { validators } from './validators.ts';
export { importMessages } from './mda-import.ts';
export {
  DEFAULT_UNITS,
  MISC_MASTERS,
  MISC_MASTER_KINDS,
  miscMasterFieldErrors,
  miscMasterMessages,
  type MiscMasterKind,
} from './misc-masters.ts';
export {
  STOCK_GROUP_CODE_PREFIX,
  STOCK_GROUP_CODE_WIDTH,
  STOCK_GROUP_TYPE,
  stockGroupFieldErrors,
  stockGroupMessages,
} from './stock-groups.ts';
export {
  STOCK_SUB_GROUP_CODE_PREFIX,
  STOCK_SUB_GROUP_CODE_WIDTH,
  STOCK_SUB_GROUP_TYPE,
  stockSubGroupFieldErrors,
  stockSubGroupMessages,
} from './stock-sub-groups.ts';
export {
  SALE_BY_OPTIONS,
  SALE_PREFIX_MAX,
  SALE_TYPE,
  SALE_TYPE_CODE_PREFIX,
  SALE_TYPE_CODE_WIDTH,
  cleanSalePrefix,
  saleTypeFieldErrors,
  saleTypeMessages,
} from './sale-types.ts';
export {
  ITEM_GST_RATES,
  ITEM_UNITS,
  TAXABLE,
  TAX_TYPES,
  stockItemFieldErrors,
  stockItemMessages,
} from './stock-items.ts';
export {
  ACTIVE,
  BANK_GROUP,
  CANCELLED,
  CASH_GROUP,
  CN_REASONS,
  CREDITORS_GROUP,
  DEBTORS_GROUP,
  DN_REASONS,
  SYSTEM_LEDGERS,
  VOUCHER_SERIES,
  amountInWords,
  amountProblem,
  cancelConfirm,
  creditNoteDraft,
  debitNoteDraft,
  fmtTotal,
  journalDraft,
  parseAmount,
  paymentDraft,
  postingMessages,
  postingProblem,
  receiptDraft,
  sum,
  sumRaw,
  systemLedgerDrCr,
  voucherMessages,
  type PostingLine,
  type VoucherDraft,
} from './vouchers.ts';
export {
  PURCHASE_BILL_SERIES,
  PURCHASE_GROUP_SEEDS,
  PURCHASE_LEDGERS,
  PURCHASE_LEDGER_SEEDS,
  SUPPLIER_GROUP,
  f2,
  gstCompute,
  gstRateNumber,
  isInterState,
  partyStateCode,
  purcLine,
  purcTotals,
  purchaseMessages,
  purchasePosting,
  purchaseProblem,
  type GstSplit,
  type PurcHeaderCheck,
  type PurcLine,
  type PurcTotals,
} from './purchases.ts';
export {
  CASH_SALE_LEDGER,
  CUSTOMER_GROUP,
  SALE_BILL_SERIES,
  SALE_GROUP_SEEDS,
  SALE_LEDGERS,
  SALE_LEDGER_SEEDS,
  saleBillPrefix,
  saleLine,
  saleMessages,
  salePosting,
  saleProblem,
  saleTotals,
  type SaleHeaderCheck,
  type SaleLine,
  type SaleTotals,
} from './sales.ts';
export {
  stjLine,
  stjTotals,
  stockJournalMessages,
  stockJournalProblem,
  type StjLine,
  type StjSide,
  type StjTotals,
} from './stock-journal.ts';
export {
  TRADING_GROUPS,
  balanceSheet,
  groupBalances,
  openingStockValue,
  profitAndLoss,
  reportMessages,
  stockRate,
  topGroupOf,
  type BalanceSheet,
  type LedgerBalance,
  type ProfitAndLoss,
  type ReportGroup,
  type StatementGroup,
} from './reports.ts';
export {
  B2CL_LIMIT,
  GST_STATES,
  gstMessages,
  gstr1,
  gstr3b,
  hsnSummary,
  placeOfSupply,
  sumTax,
  type AuditFinding,
  type B2csRow,
  type GstBill,
  type GstLine,
  type Gstr1,
  type Gstr3b,
  type Heads,
  type HsnRow,
  type InvoiceRateRow,
  type TaxSums,
} from './gst.ts';
export { parseDate, formatDmy, isInFinancialYear, financialYearLabel } from './dates.ts';
export {
  companyCode,
  companyStatutory,
  companyFieldErrors,
  companyMessages,
  yearCode,
  yearFieldErrors,
  yearMessages,
} from './company.ts';
export {
  loginMessages,
  loginFieldErrors,
  newPasswordErrors,
  SEED_ADMIN,
  ROLES,
} from './book-login.ts';
export {
  VCHR_KINDS,
  emptyDashboard,
  weekLabels,
  grouped,
  inr,
  compact,
  signed,
  pct,
  trends,
  ago,
  type DashboardData,
  type RecentTx,
  type Trend,
} from './dashboard.ts';
export {
  GROUP_TYPES,
  LEDGER_OPTIONS,
  TOP_LEVEL,
  DEFAULT_GROUPS,
  groupMessages,
  groupFieldErrors,
  groupCodePrefix,
  nextCode,
  subGroupMessages,
  subGroupFieldErrors,
  SUB_GROUP_CODE_PREFIX,
  SUB_GROUP_CODE_WIDTH,
  type GroupType,
  type DefaultGroup,
} from './groups.ts';
export {
  INDIAN_STATES,
  COUNTRIES,
  REG_TYPES,
  SALES_EXECUTIVES,
  DR_CR,
  LEDGER_CODE_PREFIX,
  LEDGER_CODE_WIDTH,
  MISC_TYPE_CITY,
  MISC_CITY_CODE_PREFIX,
  MISC_CODE_WIDTH,
  ledgerMessages,
  ledgerFieldErrors,
  type DrCr,
} from './ledgers.ts';
